name: "Image Registry"
description: "Build and Registry in GitHub Container Registry"
inputs:
  registry:
    description: "Container Registry"
    required: false
    default: 'ghcr.io'
  username:
    description: "Username for Container Registry"
    required: true
  password:
    description: "token or password for container registry"
    required: true
  image_name:
    description: "Image's name"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }} 
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}